// Code generated by protoc-gen-go. DO NOT EDIT.
// source: votes.proto

package votes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActidReq struct {
	Actid                int64     `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	Limit                *LimitReq `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Keyword              string    `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActidReq) Reset()         { *m = ActidReq{} }
func (m *ActidReq) String() string { return proto.CompactTextString(m) }
func (*ActidReq) ProtoMessage()    {}
func (*ActidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{0}
}

func (m *ActidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActidReq.Unmarshal(m, b)
}
func (m *ActidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActidReq.Marshal(b, m, deterministic)
}
func (m *ActidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActidReq.Merge(m, src)
}
func (m *ActidReq) XXX_Size() int {
	return xxx_messageInfo_ActidReq.Size(m)
}
func (m *ActidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ActidReq.DiscardUnknown(m)
}

var xxx_messageInfo_ActidReq proto.InternalMessageInfo

func (m *ActidReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

func (m *ActidReq) GetLimit() *LimitReq {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ActidReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type ActInfoReq struct {
	Actid                int64    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActInfoReq) Reset()         { *m = ActInfoReq{} }
func (m *ActInfoReq) String() string { return proto.CompactTextString(m) }
func (*ActInfoReq) ProtoMessage()    {}
func (*ActInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{1}
}

func (m *ActInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActInfoReq.Unmarshal(m, b)
}
func (m *ActInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActInfoReq.Marshal(b, m, deterministic)
}
func (m *ActInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActInfoReq.Merge(m, src)
}
func (m *ActInfoReq) XXX_Size() int {
	return xxx_messageInfo_ActInfoReq.Size(m)
}
func (m *ActInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ActInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ActInfoReq proto.InternalMessageInfo

func (m *ActInfoReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

type LimitReq struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitReq) Reset()         { *m = LimitReq{} }
func (m *LimitReq) String() string { return proto.CompactTextString(m) }
func (*LimitReq) ProtoMessage()    {}
func (*LimitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{2}
}

func (m *LimitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitReq.Unmarshal(m, b)
}
func (m *LimitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitReq.Marshal(b, m, deterministic)
}
func (m *LimitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitReq.Merge(m, src)
}
func (m *LimitReq) XXX_Size() int {
	return xxx_messageInfo_LimitReq.Size(m)
}
func (m *LimitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitReq.DiscardUnknown(m)
}

var xxx_messageInfo_LimitReq proto.InternalMessageInfo

func (m *LimitReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *LimitReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type EnrollInfoReq struct {
	Aeid                 int64    `protobuf:"varint,1,opt,name=aeid,proto3" json:"aeid,omitempty"`
	Actid                int64    `protobuf:"varint,2,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollInfoReq) Reset()         { *m = EnrollInfoReq{} }
func (m *EnrollInfoReq) String() string { return proto.CompactTextString(m) }
func (*EnrollInfoReq) ProtoMessage()    {}
func (*EnrollInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{3}
}

func (m *EnrollInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollInfoReq.Unmarshal(m, b)
}
func (m *EnrollInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollInfoReq.Marshal(b, m, deterministic)
}
func (m *EnrollInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollInfoReq.Merge(m, src)
}
func (m *EnrollInfoReq) XXX_Size() int {
	return xxx_messageInfo_EnrollInfoReq.Size(m)
}
func (m *EnrollInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollInfoReq proto.InternalMessageInfo

func (m *EnrollInfoReq) GetAeid() int64 {
	if m != nil {
		return m.Aeid
	}
	return 0
}

func (m *EnrollInfoReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

//报名 请求
type EnrollReq struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Images               string   `protobuf:"bytes,7,opt,name=images,proto3" json:"images,omitempty"`
	Descr                string   `protobuf:"bytes,8,opt,name=descr,proto3" json:"descr,omitempty"`
	Actid                int64    `protobuf:"varint,9,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollReq) Reset()         { *m = EnrollReq{} }
func (m *EnrollReq) String() string { return proto.CompactTextString(m) }
func (*EnrollReq) ProtoMessage()    {}
func (*EnrollReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{4}
}

func (m *EnrollReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollReq.Unmarshal(m, b)
}
func (m *EnrollReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollReq.Marshal(b, m, deterministic)
}
func (m *EnrollReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollReq.Merge(m, src)
}
func (m *EnrollReq) XXX_Size() int {
	return xxx_messageInfo_EnrollReq.Size(m)
}
func (m *EnrollReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollReq proto.InternalMessageInfo

func (m *EnrollReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *EnrollReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *EnrollReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *EnrollReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *EnrollReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnrollReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EnrollReq) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *EnrollReq) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *EnrollReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

//报名返回
type EnrollResp struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Images               []string `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Descr                string   `protobuf:"bytes,8,opt,name=descr,proto3" json:"descr,omitempty"`
	Votecount            int64    `protobuf:"varint,9,opt,name=votecount,proto3" json:"votecount,omitempty"`
	Viewcount            int64    `protobuf:"varint,10,opt,name=viewcount,proto3" json:"viewcount,omitempty"`
	Aeid                 int64    `protobuf:"varint,11,opt,name=aeid,proto3" json:"aeid,omitempty"`
	Actid                int64    `protobuf:"varint,12,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollResp) Reset()         { *m = EnrollResp{} }
func (m *EnrollResp) String() string { return proto.CompactTextString(m) }
func (*EnrollResp) ProtoMessage()    {}
func (*EnrollResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{5}
}

func (m *EnrollResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollResp.Unmarshal(m, b)
}
func (m *EnrollResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollResp.Marshal(b, m, deterministic)
}
func (m *EnrollResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollResp.Merge(m, src)
}
func (m *EnrollResp) XXX_Size() int {
	return xxx_messageInfo_EnrollResp.Size(m)
}
func (m *EnrollResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollResp.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollResp proto.InternalMessageInfo

func (m *EnrollResp) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *EnrollResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *EnrollResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *EnrollResp) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *EnrollResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnrollResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EnrollResp) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *EnrollResp) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *EnrollResp) GetVotecount() int64 {
	if m != nil {
		return m.Votecount
	}
	return 0
}

func (m *EnrollResp) GetViewcount() int64 {
	if m != nil {
		return m.Viewcount
	}
	return 0
}

func (m *EnrollResp) GetAeid() int64 {
	if m != nil {
		return m.Aeid
	}
	return 0
}

func (m *EnrollResp) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

//返回列表
type EnrollListResp struct {
	Data                 []*EnrollResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EnrollListResp) Reset()         { *m = EnrollListResp{} }
func (m *EnrollListResp) String() string { return proto.CompactTextString(m) }
func (*EnrollListResp) ProtoMessage()    {}
func (*EnrollListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{6}
}

func (m *EnrollListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollListResp.Unmarshal(m, b)
}
func (m *EnrollListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollListResp.Marshal(b, m, deterministic)
}
func (m *EnrollListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollListResp.Merge(m, src)
}
func (m *EnrollListResp) XXX_Size() int {
	return xxx_messageInfo_EnrollListResp.Size(m)
}
func (m *EnrollListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollListResp.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollListResp proto.InternalMessageInfo

func (m *EnrollListResp) GetData() []*EnrollResp {
	if m != nil {
		return m.Data
	}
	return nil
}

//投票
type VotesReq struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Actid                int64    `protobuf:"varint,5,opt,name=actid,proto3" json:"actid,omitempty"`
	Aeid                 int64    `protobuf:"varint,6,opt,name=aeid,proto3" json:"aeid,omitempty"`
	Ip                   string   `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VotesReq) Reset()         { *m = VotesReq{} }
func (m *VotesReq) String() string { return proto.CompactTextString(m) }
func (*VotesReq) ProtoMessage()    {}
func (*VotesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{7}
}

func (m *VotesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotesReq.Unmarshal(m, b)
}
func (m *VotesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotesReq.Marshal(b, m, deterministic)
}
func (m *VotesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotesReq.Merge(m, src)
}
func (m *VotesReq) XXX_Size() int {
	return xxx_messageInfo_VotesReq.Size(m)
}
func (m *VotesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VotesReq.DiscardUnknown(m)
}

var xxx_messageInfo_VotesReq proto.InternalMessageInfo

func (m *VotesReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *VotesReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *VotesReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *VotesReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *VotesReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

func (m *VotesReq) GetAeid() int64 {
	if m != nil {
		return m.Aeid
	}
	return 0
}

func (m *VotesReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

//返回票数
type VotesResp struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Avid                 int64    `protobuf:"varint,5,opt,name=avid,proto3" json:"avid,omitempty"`
	Aeid                 int64    `protobuf:"varint,6,opt,name=aeid,proto3" json:"aeid,omitempty"`
	Votecount            int64    `protobuf:"varint,7,opt,name=votecount,proto3" json:"votecount,omitempty"`
	Viewcount            int64    `protobuf:"varint,8,opt,name=viewcount,proto3" json:"viewcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VotesResp) Reset()         { *m = VotesResp{} }
func (m *VotesResp) String() string { return proto.CompactTextString(m) }
func (*VotesResp) ProtoMessage()    {}
func (*VotesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{8}
}

func (m *VotesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotesResp.Unmarshal(m, b)
}
func (m *VotesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotesResp.Marshal(b, m, deterministic)
}
func (m *VotesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotesResp.Merge(m, src)
}
func (m *VotesResp) XXX_Size() int {
	return xxx_messageInfo_VotesResp.Size(m)
}
func (m *VotesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VotesResp.DiscardUnknown(m)
}

var xxx_messageInfo_VotesResp proto.InternalMessageInfo

func (m *VotesResp) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *VotesResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *VotesResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *VotesResp) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *VotesResp) GetAvid() int64 {
	if m != nil {
		return m.Avid
	}
	return 0
}

func (m *VotesResp) GetAeid() int64 {
	if m != nil {
		return m.Aeid
	}
	return 0
}

func (m *VotesResp) GetVotecount() int64 {
	if m != nil {
		return m.Votecount
	}
	return 0
}

func (m *VotesResp) GetViewcount() int64 {
	if m != nil {
		return m.Viewcount
	}
	return 0
}

//返回活动信息
type ActInfoResp struct {
	Actid                int64    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Descr                string   `protobuf:"bytes,5,opt,name=descr,proto3" json:"descr,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	StartDate            int64    `protobuf:"varint,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EnrollDate           int64    `protobuf:"varint,8,opt,name=enroll_date,json=enrollDate,proto3" json:"enroll_date,omitempty"`
	EndDate              int64    `protobuf:"varint,9,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Votecount            int64    `protobuf:"varint,10,opt,name=votecount,proto3" json:"votecount,omitempty"`
	Viewcount            int64    `protobuf:"varint,11,opt,name=viewcount,proto3" json:"viewcount,omitempty"`
	Type                 int64    `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`
	Num                  int64    `protobuf:"varint,13,opt,name=num,proto3" json:"num,omitempty"`
	Enrollcount          int64    `protobuf:"varint,14,opt,name=enrollcount,proto3" json:"enrollcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActInfoResp) Reset()         { *m = ActInfoResp{} }
func (m *ActInfoResp) String() string { return proto.CompactTextString(m) }
func (*ActInfoResp) ProtoMessage()    {}
func (*ActInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6b6b7bef3da532, []int{9}
}

func (m *ActInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActInfoResp.Unmarshal(m, b)
}
func (m *ActInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActInfoResp.Marshal(b, m, deterministic)
}
func (m *ActInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActInfoResp.Merge(m, src)
}
func (m *ActInfoResp) XXX_Size() int {
	return xxx_messageInfo_ActInfoResp.Size(m)
}
func (m *ActInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ActInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ActInfoResp proto.InternalMessageInfo

func (m *ActInfoResp) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

func (m *ActInfoResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *ActInfoResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *ActInfoResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ActInfoResp) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *ActInfoResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ActInfoResp) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *ActInfoResp) GetEnrollDate() int64 {
	if m != nil {
		return m.EnrollDate
	}
	return 0
}

func (m *ActInfoResp) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *ActInfoResp) GetVotecount() int64 {
	if m != nil {
		return m.Votecount
	}
	return 0
}

func (m *ActInfoResp) GetViewcount() int64 {
	if m != nil {
		return m.Viewcount
	}
	return 0
}

func (m *ActInfoResp) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ActInfoResp) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *ActInfoResp) GetEnrollcount() int64 {
	if m != nil {
		return m.Enrollcount
	}
	return 0
}

func init() {
	proto.RegisterType((*ActidReq)(nil), "votes.ActidReq")
	proto.RegisterType((*ActInfoReq)(nil), "votes.ActInfoReq")
	proto.RegisterType((*LimitReq)(nil), "votes.LimitReq")
	proto.RegisterType((*EnrollInfoReq)(nil), "votes.EnrollInfoReq")
	proto.RegisterType((*EnrollReq)(nil), "votes.EnrollReq")
	proto.RegisterType((*EnrollResp)(nil), "votes.EnrollResp")
	proto.RegisterType((*EnrollListResp)(nil), "votes.EnrollListResp")
	proto.RegisterType((*VotesReq)(nil), "votes.VotesReq")
	proto.RegisterType((*VotesResp)(nil), "votes.VotesResp")
	proto.RegisterType((*ActInfoResp)(nil), "votes.ActInfoResp")
}

func init() { proto.RegisterFile("votes.proto", fileDescriptor_9f6b6b7bef3da532) }

var fileDescriptor_9f6b6b7bef3da532 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6a, 0xdc, 0x3e,
	0x10, 0xc7, 0xf6, 0xda, 0x6b, 0x8f, 0xff, 0xd9, 0x24, 0x22, 0xff, 0xe0, 0x86, 0x96, 0x2e, 0x86,
	0xc0, 0x52, 0x68, 0x0e, 0x29, 0x34, 0xe9, 0x31, 0xd0, 0x12, 0x02, 0x39, 0xf9, 0x90, 0x6b, 0x51,
	0xd6, 0x4a, 0x11, 0xdd, 0xb5, 0x1d, 0x4b, 0xce, 0xb2, 0x7d, 0x8e, 0x9e, 0xfb, 0x2a, 0xbd, 0xf6,
	0xd2, 0x77, 0xe9, 0x23, 0x14, 0x8d, 0x24, 0xdb, 0xbb, 0xdd, 0xa4, 0xb9, 0x04, 0x7a, 0x9b, 0x0f,
	0xcd, 0xc7, 0x6f, 0xe6, 0x27, 0x09, 0xe2, 0xbb, 0x52, 0x32, 0x71, 0x54, 0xd5, 0xa5, 0x2c, 0x89,
	0x8f, 0x4a, 0x4a, 0x21, 0x3c, 0x9b, 0x4a, 0x9e, 0x67, 0xec, 0x96, 0xec, 0x81, 0x4f, 0x95, 0x9c,
	0x38, 0x63, 0x67, 0xe2, 0x65, 0x5a, 0x21, 0x87, 0xe0, 0xcf, 0xf8, 0x9c, 0xcb, 0xc4, 0x1d, 0x3b,
	0x93, 0xf8, 0x78, 0xfb, 0x48, 0x67, 0xb9, 0x54, 0xb6, 0x8c, 0xdd, 0x66, 0xda, 0x4b, 0x12, 0x18,
	0x7e, 0x66, 0xcb, 0x45, 0x59, 0xe7, 0x89, 0x37, 0x76, 0x26, 0x51, 0x66, 0xd5, 0x34, 0x05, 0x38,
	0x9b, 0xca, 0x8b, 0xe2, 0xa6, 0xbc, 0xb7, 0x48, 0xfa, 0x16, 0x42, 0x9b, 0x90, 0xec, 0x43, 0x50,
	0xde, 0xdc, 0x08, 0x26, 0xcd, 0x11, 0xa3, 0x11, 0x02, 0x03, 0xc1, 0xbf, 0x30, 0xec, 0xc3, 0xcb,
	0x50, 0x4e, 0xdf, 0xc1, 0xd6, 0x87, 0xa2, 0x2e, 0x67, 0x33, 0x9b, 0x9e, 0xc0, 0x80, 0xb2, 0x36,
	0x3b, 0xca, 0x5d, 0x49, 0xb7, 0x5f, 0xf2, 0xa7, 0x03, 0x91, 0x8e, 0xb5, 0x71, 0x4d, 0x2f, 0xae,
	0xe1, 0xb9, 0xb2, 0x5d, 0xb3, 0x36, 0x0c, 0x65, 0x95, 0xab, 0x92, 0x4b, 0xae, 0x41, 0x7a, 0x99,
	0x56, 0xc8, 0x0e, 0x78, 0x2a, 0x78, 0x80, 0x36, 0xcf, 0xc4, 0x16, 0x74, 0xce, 0x12, 0x1f, 0x67,
	0x81, 0xb2, 0x1a, 0x11, 0xcd, 0xf3, 0x9a, 0x09, 0x91, 0x04, 0x7a, 0x44, 0x46, 0x55, 0x90, 0xf9,
	0x9c, 0x7e, 0x62, 0x22, 0x19, 0xa2, 0xc3, 0x68, 0xaa, 0x5a, 0xce, 0xc4, 0xb4, 0x4e, 0x42, 0x34,
	0x6b, 0xa5, 0xc3, 0x13, 0xf5, 0xf1, 0x7c, 0x73, 0x01, 0x2c, 0x1e, 0x51, 0xfd, 0x43, 0x80, 0xbc,
	0xbf, 0x02, 0x7a, 0x0e, 0x91, 0x22, 0xd5, 0xb4, 0x6c, 0x0a, 0x69, 0x40, 0x75, 0x06, 0xf4, 0x72,
	0xb6, 0xd0, 0x5e, 0x30, 0x5e, 0x6b, 0x68, 0x17, 0x1e, 0x6f, 0x5a, 0xf8, 0x7f, 0xfd, 0x01, 0x9d,
	0xc0, 0x48, 0xcf, 0xe7, 0x92, 0x0b, 0x89, 0x33, 0x3a, 0x84, 0x41, 0x4e, 0x25, 0x4d, 0x9c, 0xb1,
	0x37, 0x89, 0x8f, 0x77, 0x0d, 0xb3, 0xbb, 0x21, 0x66, 0xe8, 0x4e, 0xbf, 0x3a, 0x10, 0x5e, 0x29,
	0xd7, 0x53, 0x10, 0xa5, 0xed, 0xd5, 0xef, 0x5f, 0x3a, 0x8b, 0x2a, 0xe8, 0xa1, 0x1a, 0x81, 0xcb,
	0x2b, 0x43, 0x10, 0x97, 0x57, 0xe9, 0x77, 0x07, 0x22, 0xd3, 0xd6, 0xd3, 0xec, 0x9b, 0xde, 0xb5,
	0x6d, 0xa1, 0xbc, 0xb1, 0xab, 0x95, 0xdd, 0x0d, 0x1f, 0xdc, 0x5d, 0xb8, 0xb6, 0xbb, 0xf4, 0x97,
	0x0b, 0x71, 0xfb, 0x34, 0x88, 0xea, 0x9e, 0x07, 0xe8, 0xf1, 0x28, 0xf6, 0xc0, 0x97, 0x5c, 0xce,
	0x18, 0xe2, 0x88, 0x32, 0xad, 0x74, 0x9c, 0xf3, 0xfb, 0x9c, 0xdb, 0x87, 0x40, 0x48, 0x2a, 0x1b,
	0x61, 0xd0, 0x18, 0x8d, 0xbc, 0x00, 0x10, 0x92, 0xd6, 0xf2, 0x63, 0x4e, 0x25, 0xb3, 0x80, 0xd0,
	0xf2, 0x9e, 0x4a, 0x46, 0x5e, 0x42, 0xcc, 0x90, 0x1f, 0xda, 0xaf, 0x21, 0x81, 0x36, 0xe1, 0x81,
	0x67, 0x10, 0xb2, 0x22, 0xd7, 0x5e, 0x4d, 0xe5, 0x21, 0x2b, 0x72, 0x74, 0xad, 0x8c, 0x0a, 0x1e,
	0x1c, 0x55, 0xbc, 0x81, 0xe6, 0x72, 0x59, 0x31, 0xc3, 0x68, 0x94, 0xd5, 0xd2, 0x8a, 0x66, 0x9e,
	0x6c, 0xe9, 0xa5, 0x15, 0xcd, 0x9c, 0x8c, 0x6d, 0x77, 0x3a, 0xcb, 0x08, 0x3d, 0x7d, 0xd3, 0xf1,
	0x0f, 0x17, 0x7c, 0x24, 0x0d, 0x39, 0x85, 0xad, 0x73, 0x26, 0xbb, 0xd7, 0x93, 0xec, 0xad, 0xf0,
	0xdf, 0x3c, 0xa8, 0x07, 0x7f, 0xde, 0x0a, 0x72, 0xd2, 0x8b, 0x54, 0x77, 0x89, 0xd8, 0x3f, 0xc1,
	0xfe, 0x24, 0x07, 0xff, 0xaf, 0x04, 0xb5, 0xf7, 0xed, 0x14, 0xb6, 0xcf, 0x99, 0x54, 0xa7, 0xee,
	0xb8, 0x5c, 0x62, 0xd1, 0xdd, 0x2e, 0xd4, 0x56, 0x24, 0xeb, 0x26, 0x51, 0x91, 0xd7, 0x10, 0xe8,
	0x5c, 0x64, 0x67, 0xad, 0x9f, 0x8d, 0x1d, 0xbe, 0xb2, 0x20, 0x6d, 0x67, 0xf6, 0xfa, 0x1e, 0xec,
	0xac, 0x1a, 0x10, 0xcd, 0xe8, 0xa2, 0x98, 0xd6, 0xba, 0xab, 0x2b, 0xce, 0x16, 0x8f, 0xec, 0xe9,
	0x3a, 0xc0, 0x8f, 0xf4, 0xcd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0xfe, 0x4f, 0x23, 0x57,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VotesClient is the client API for Votes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VotesClient interface {
	//获取作品信息
	GetEnrollInfo(ctx context.Context, in *EnrollInfoReq, opts ...grpc.CallOption) (*EnrollResp, error)
	//获取 作品列表
	GetEnrollList(ctx context.Context, in *ActidReq, opts ...grpc.CallOption) (*EnrollListResp, error)
	//获取 活动信息
	GetActivityInfo(ctx context.Context, in *ActInfoReq, opts ...grpc.CallOption) (*ActInfoResp, error)
	//报名
	Enroll(ctx context.Context, in *EnrollReq, opts ...grpc.CallOption) (*EnrollResp, error)
	//投票
	Votes(ctx context.Context, in *VotesReq, opts ...grpc.CallOption) (*VotesResp, error)
	//增加活动的爆光量
	IncrActiviView(ctx context.Context, in *ActInfoReq, opts ...grpc.CallOption) (*ActInfoResp, error)
}

type votesClient struct {
	cc *grpc.ClientConn
}

func NewVotesClient(cc *grpc.ClientConn) VotesClient {
	return &votesClient{cc}
}

func (c *votesClient) GetEnrollInfo(ctx context.Context, in *EnrollInfoReq, opts ...grpc.CallOption) (*EnrollResp, error) {
	out := new(EnrollResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/GetEnrollInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesClient) GetEnrollList(ctx context.Context, in *ActidReq, opts ...grpc.CallOption) (*EnrollListResp, error) {
	out := new(EnrollListResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/GetEnrollList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesClient) GetActivityInfo(ctx context.Context, in *ActInfoReq, opts ...grpc.CallOption) (*ActInfoResp, error) {
	out := new(ActInfoResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/GetActivityInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesClient) Enroll(ctx context.Context, in *EnrollReq, opts ...grpc.CallOption) (*EnrollResp, error) {
	out := new(EnrollResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/Enroll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesClient) Votes(ctx context.Context, in *VotesReq, opts ...grpc.CallOption) (*VotesResp, error) {
	out := new(VotesResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/Votes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votesClient) IncrActiviView(ctx context.Context, in *ActInfoReq, opts ...grpc.CallOption) (*ActInfoResp, error) {
	out := new(ActInfoResp)
	err := c.cc.Invoke(ctx, "/votes.Votes/IncrActiviView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VotesServer is the server API for Votes service.
type VotesServer interface {
	//获取作品信息
	GetEnrollInfo(context.Context, *EnrollInfoReq) (*EnrollResp, error)
	//获取 作品列表
	GetEnrollList(context.Context, *ActidReq) (*EnrollListResp, error)
	//获取 活动信息
	GetActivityInfo(context.Context, *ActInfoReq) (*ActInfoResp, error)
	//报名
	Enroll(context.Context, *EnrollReq) (*EnrollResp, error)
	//投票
	Votes(context.Context, *VotesReq) (*VotesResp, error)
	//增加活动的爆光量
	IncrActiviView(context.Context, *ActInfoReq) (*ActInfoResp, error)
}

// UnimplementedVotesServer can be embedded to have forward compatible implementations.
type UnimplementedVotesServer struct {
}

func (*UnimplementedVotesServer) GetEnrollInfo(ctx context.Context, req *EnrollInfoReq) (*EnrollResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollInfo not implemented")
}
func (*UnimplementedVotesServer) GetEnrollList(ctx context.Context, req *ActidReq) (*EnrollListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollList not implemented")
}
func (*UnimplementedVotesServer) GetActivityInfo(ctx context.Context, req *ActInfoReq) (*ActInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityInfo not implemented")
}
func (*UnimplementedVotesServer) Enroll(ctx context.Context, req *EnrollReq) (*EnrollResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (*UnimplementedVotesServer) Votes(ctx context.Context, req *VotesReq) (*VotesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Votes not implemented")
}
func (*UnimplementedVotesServer) IncrActiviView(ctx context.Context, req *ActInfoReq) (*ActInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrActiviView not implemented")
}

func RegisterVotesServer(s *grpc.Server, srv VotesServer) {
	s.RegisterService(&_Votes_serviceDesc, srv)
}

func _Votes_GetEnrollInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).GetEnrollInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/GetEnrollInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).GetEnrollInfo(ctx, req.(*EnrollInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Votes_GetEnrollList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).GetEnrollList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/GetEnrollList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).GetEnrollList(ctx, req.(*ActidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Votes_GetActivityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).GetActivityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/GetActivityInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).GetActivityInfo(ctx, req.(*ActInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Votes_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/Enroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).Enroll(ctx, req.(*EnrollReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Votes_Votes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).Votes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/Votes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).Votes(ctx, req.(*VotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Votes_IncrActiviView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotesServer).IncrActiviView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votes.Votes/IncrActiviView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotesServer).IncrActiviView(ctx, req.(*ActInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Votes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "votes.Votes",
	HandlerType: (*VotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnrollInfo",
			Handler:    _Votes_GetEnrollInfo_Handler,
		},
		{
			MethodName: "GetEnrollList",
			Handler:    _Votes_GetEnrollList_Handler,
		},
		{
			MethodName: "GetActivityInfo",
			Handler:    _Votes_GetActivityInfo_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _Votes_Enroll_Handler,
		},
		{
			MethodName: "Votes",
			Handler:    _Votes_Votes_Handler,
		},
		{
			MethodName: "IncrActiviView",
			Handler:    _Votes_IncrActiviView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "votes.proto",
}
