// Code generated by protoc-gen-go. DO NOT EDIT.
// source: questions.proto

package questions

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Response struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type ActivitiesReq struct {
	Actid                int64    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivitiesReq) Reset()         { *m = ActivitiesReq{} }
func (m *ActivitiesReq) String() string { return proto.CompactTextString(m) }
func (*ActivitiesReq) ProtoMessage()    {}
func (*ActivitiesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{2}
}

func (m *ActivitiesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesReq.Unmarshal(m, b)
}
func (m *ActivitiesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesReq.Marshal(b, m, deterministic)
}
func (m *ActivitiesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesReq.Merge(m, src)
}
func (m *ActivitiesReq) XXX_Size() int {
	return xxx_messageInfo_ActivitiesReq.Size(m)
}
func (m *ActivitiesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesReq proto.InternalMessageInfo

func (m *ActivitiesReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

//返回问答抽奖活动信息
type ActInfoResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Descr                string   `protobuf:"bytes,5,opt,name=descr,proto3" json:"descr,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	StartDate            int64    `protobuf:"varint,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              int64    `protobuf:"varint,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GetScore             int64    `protobuf:"varint,9,opt,name=get_score,json=getScore,proto3" json:"get_score,omitempty"`
	Header               string   `protobuf:"bytes,10,opt,name=header,proto3" json:"header,omitempty"`
	Des                  string   `protobuf:"bytes,11,opt,name=des,proto3" json:"des,omitempty"`
	Image                string   `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"`
	Rule                 string   `protobuf:"bytes,13,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActInfoResp) Reset()         { *m = ActInfoResp{} }
func (m *ActInfoResp) String() string { return proto.CompactTextString(m) }
func (*ActInfoResp) ProtoMessage()    {}
func (*ActInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{3}
}

func (m *ActInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActInfoResp.Unmarshal(m, b)
}
func (m *ActInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActInfoResp.Marshal(b, m, deterministic)
}
func (m *ActInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActInfoResp.Merge(m, src)
}
func (m *ActInfoResp) XXX_Size() int {
	return xxx_messageInfo_ActInfoResp.Size(m)
}
func (m *ActInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ActInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ActInfoResp proto.InternalMessageInfo

func (m *ActInfoResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActInfoResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *ActInfoResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *ActInfoResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ActInfoResp) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *ActInfoResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ActInfoResp) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *ActInfoResp) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *ActInfoResp) GetGetScore() int64 {
	if m != nil {
		return m.GetScore
	}
	return 0
}

func (m *ActInfoResp) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *ActInfoResp) GetDes() string {
	if m != nil {
		return m.Des
	}
	return ""
}

func (m *ActInfoResp) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ActInfoResp) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

type AwardInfoResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Des                  string   `protobuf:"bytes,5,opt,name=des,proto3" json:"des,omitempty"`
	Number               int64    `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	StartProbability     int64    `protobuf:"varint,7,opt,name=start_probability,json=startProbability,proto3" json:"start_probability,omitempty"`
	EndProbability       int64    `protobuf:"varint,8,opt,name=end_probability,json=endProbability,proto3" json:"end_probability,omitempty"`
	ActivityId           int64    `protobuf:"varint,9,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Header               string   `protobuf:"bytes,10,opt,name=header,proto3" json:"header,omitempty"`
	Image                string   `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AwardInfoResp) Reset()         { *m = AwardInfoResp{} }
func (m *AwardInfoResp) String() string { return proto.CompactTextString(m) }
func (*AwardInfoResp) ProtoMessage()    {}
func (*AwardInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{4}
}

func (m *AwardInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AwardInfoResp.Unmarshal(m, b)
}
func (m *AwardInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AwardInfoResp.Marshal(b, m, deterministic)
}
func (m *AwardInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwardInfoResp.Merge(m, src)
}
func (m *AwardInfoResp) XXX_Size() int {
	return xxx_messageInfo_AwardInfoResp.Size(m)
}
func (m *AwardInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AwardInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_AwardInfoResp proto.InternalMessageInfo

func (m *AwardInfoResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AwardInfoResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *AwardInfoResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *AwardInfoResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AwardInfoResp) GetDes() string {
	if m != nil {
		return m.Des
	}
	return ""
}

func (m *AwardInfoResp) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AwardInfoResp) GetStartProbability() int64 {
	if m != nil {
		return m.StartProbability
	}
	return 0
}

func (m *AwardInfoResp) GetEndProbability() int64 {
	if m != nil {
		return m.EndProbability
	}
	return 0
}

func (m *AwardInfoResp) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *AwardInfoResp) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *AwardInfoResp) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type AwardListResp struct {
	Data                 []*AwardInfoResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AwardListResp) Reset()         { *m = AwardListResp{} }
func (m *AwardListResp) String() string { return proto.CompactTextString(m) }
func (*AwardListResp) ProtoMessage()    {}
func (*AwardListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{5}
}

func (m *AwardListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AwardListResp.Unmarshal(m, b)
}
func (m *AwardListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AwardListResp.Marshal(b, m, deterministic)
}
func (m *AwardListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwardListResp.Merge(m, src)
}
func (m *AwardListResp) XXX_Size() int {
	return xxx_messageInfo_AwardListResp.Size(m)
}
func (m *AwardListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AwardListResp.DiscardUnknown(m)
}

var xxx_messageInfo_AwardListResp proto.InternalMessageInfo

func (m *AwardListResp) GetData() []*AwardInfoResp {
	if m != nil {
		return m.Data
	}
	return nil
}

type QuestionsResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Options              string   `protobuf:"bytes,4,opt,name=Options,proto3" json:"Options,omitempty"`
	Corrent              string   `protobuf:"bytes,5,opt,name=Corrent,proto3" json:"Corrent,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Question             string   `protobuf:"bytes,7,opt,name=Question,proto3" json:"Question,omitempty"`
	ActivityId           int64    `protobuf:"varint,8,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionsResp) Reset()         { *m = QuestionsResp{} }
func (m *QuestionsResp) String() string { return proto.CompactTextString(m) }
func (*QuestionsResp) ProtoMessage()    {}
func (*QuestionsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{6}
}

func (m *QuestionsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionsResp.Unmarshal(m, b)
}
func (m *QuestionsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionsResp.Marshal(b, m, deterministic)
}
func (m *QuestionsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionsResp.Merge(m, src)
}
func (m *QuestionsResp) XXX_Size() int {
	return xxx_messageInfo_QuestionsResp.Size(m)
}
func (m *QuestionsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionsResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionsResp proto.InternalMessageInfo

func (m *QuestionsResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QuestionsResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *QuestionsResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *QuestionsResp) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *QuestionsResp) GetCorrent() string {
	if m != nil {
		return m.Corrent
	}
	return ""
}

func (m *QuestionsResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QuestionsResp) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *QuestionsResp) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

type QuestionsListResp struct {
	Data                 []*QuestionsResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QuestionsListResp) Reset()         { *m = QuestionsListResp{} }
func (m *QuestionsListResp) String() string { return proto.CompactTextString(m) }
func (*QuestionsListResp) ProtoMessage()    {}
func (*QuestionsListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{7}
}

func (m *QuestionsListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionsListResp.Unmarshal(m, b)
}
func (m *QuestionsListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionsListResp.Marshal(b, m, deterministic)
}
func (m *QuestionsListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionsListResp.Merge(m, src)
}
func (m *QuestionsListResp) XXX_Size() int {
	return xxx_messageInfo_QuestionsListResp.Size(m)
}
func (m *QuestionsListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionsListResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionsListResp proto.InternalMessageInfo

func (m *QuestionsListResp) GetData() []*QuestionsResp {
	if m != nil {
		return m.Data
	}
	return nil
}

//答案提交
type QuestionsAnswerReq struct {
	Beid                 int64    `protobuf:"varint,1,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,2,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Answers              string   `protobuf:"bytes,5,opt,name=answers,proto3" json:"answers,omitempty"`
	Score                string   `protobuf:"bytes,6,opt,name=score,proto3" json:"score,omitempty"`
	Auid                 int64    `protobuf:"varint,7,opt,name=Auid,proto3" json:"Auid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionsAnswerReq) Reset()         { *m = QuestionsAnswerReq{} }
func (m *QuestionsAnswerReq) String() string { return proto.CompactTextString(m) }
func (*QuestionsAnswerReq) ProtoMessage()    {}
func (*QuestionsAnswerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{8}
}

func (m *QuestionsAnswerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionsAnswerReq.Unmarshal(m, b)
}
func (m *QuestionsAnswerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionsAnswerReq.Marshal(b, m, deterministic)
}
func (m *QuestionsAnswerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionsAnswerReq.Merge(m, src)
}
func (m *QuestionsAnswerReq) XXX_Size() int {
	return xxx_messageInfo_QuestionsAnswerReq.Size(m)
}
func (m *QuestionsAnswerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionsAnswerReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionsAnswerReq proto.InternalMessageInfo

func (m *QuestionsAnswerReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *QuestionsAnswerReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *QuestionsAnswerReq) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *QuestionsAnswerReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *QuestionsAnswerReq) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *QuestionsAnswerReq) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *QuestionsAnswerReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

//问答返回
type QuestionsAnswerResp struct {
	AnswerId             int64    `protobuf:"varint,1,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionsAnswerResp) Reset()         { *m = QuestionsAnswerResp{} }
func (m *QuestionsAnswerResp) String() string { return proto.CompactTextString(m) }
func (*QuestionsAnswerResp) ProtoMessage()    {}
func (*QuestionsAnswerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{9}
}

func (m *QuestionsAnswerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionsAnswerResp.Unmarshal(m, b)
}
func (m *QuestionsAnswerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionsAnswerResp.Marshal(b, m, deterministic)
}
func (m *QuestionsAnswerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionsAnswerResp.Merge(m, src)
}
func (m *QuestionsAnswerResp) XXX_Size() int {
	return xxx_messageInfo_QuestionsAnswerResp.Size(m)
}
func (m *QuestionsAnswerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionsAnswerResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionsAnswerResp proto.InternalMessageInfo

func (m *QuestionsAnswerResp) GetAnswerId() int64 {
	if m != nil {
		return m.AnswerId
	}
	return 0
}

func (m *QuestionsAnswerResp) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

//得分
type GradeReq struct {
	Actid                int64    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Auid                 int64    `protobuf:"varint,3,opt,name=Auid,proto3" json:"Auid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradeReq) Reset()         { *m = GradeReq{} }
func (m *GradeReq) String() string { return proto.CompactTextString(m) }
func (*GradeReq) ProtoMessage()    {}
func (*GradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{10}
}

func (m *GradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeReq.Unmarshal(m, b)
}
func (m *GradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeReq.Marshal(b, m, deterministic)
}
func (m *GradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeReq.Merge(m, src)
}
func (m *GradeReq) XXX_Size() int {
	return xxx_messageInfo_GradeReq.Size(m)
}
func (m *GradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GradeReq proto.InternalMessageInfo

func (m *GradeReq) GetActid() int64 {
	if m != nil {
		return m.Actid
	}
	return 0
}

func (m *GradeReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GradeReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

//抽奖
type TurnTableReq struct {
	Beid                 int64    `protobuf:"varint,1,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,2,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Auid                 int64    `protobuf:"varint,5,opt,name=Auid,proto3" json:"Auid,omitempty"`
	AnswerId             int64    `protobuf:"varint,6,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnTableReq) Reset()         { *m = TurnTableReq{} }
func (m *TurnTableReq) String() string { return proto.CompactTextString(m) }
func (*TurnTableReq) ProtoMessage()    {}
func (*TurnTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{11}
}

func (m *TurnTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnTableReq.Unmarshal(m, b)
}
func (m *TurnTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnTableReq.Marshal(b, m, deterministic)
}
func (m *TurnTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnTableReq.Merge(m, src)
}
func (m *TurnTableReq) XXX_Size() int {
	return xxx_messageInfo_TurnTableReq.Size(m)
}
func (m *TurnTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_TurnTableReq proto.InternalMessageInfo

func (m *TurnTableReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *TurnTableReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *TurnTableReq) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *TurnTableReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TurnTableReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *TurnTableReq) GetAnswerId() int64 {
	if m != nil {
		return m.AnswerId
	}
	return 0
}

//兑奖
type ConvertReq struct {
	Beid                 int64    `protobuf:"varint,1,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,2,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Auid                 int64    `protobuf:"varint,5,opt,name=Auid,proto3" json:"Auid,omitempty"`
	LotteryId            int64    `protobuf:"varint,6,opt,name=LotteryId,proto3" json:"LotteryId,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertReq) Reset()         { *m = ConvertReq{} }
func (m *ConvertReq) String() string { return proto.CompactTextString(m) }
func (*ConvertReq) ProtoMessage()    {}
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{12}
}

func (m *ConvertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertReq.Unmarshal(m, b)
}
func (m *ConvertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertReq.Marshal(b, m, deterministic)
}
func (m *ConvertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertReq.Merge(m, src)
}
func (m *ConvertReq) XXX_Size() int {
	return xxx_messageInfo_ConvertReq.Size(m)
}
func (m *ConvertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertReq proto.InternalMessageInfo

func (m *ConvertReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *ConvertReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *ConvertReq) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ConvertReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ConvertReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *ConvertReq) GetLotteryId() int64 {
	if m != nil {
		return m.LotteryId
	}
	return 0
}

func (m *ConvertReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConvertReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ConvertResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LotteryId            int64    `protobuf:"varint,2,opt,name=LotteryId,proto3" json:"LotteryId,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertResp) Reset()         { *m = ConvertResp{} }
func (m *ConvertResp) String() string { return proto.CompactTextString(m) }
func (*ConvertResp) ProtoMessage()    {}
func (*ConvertResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4cafc9881e02ba, []int{13}
}

func (m *ConvertResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertResp.Unmarshal(m, b)
}
func (m *ConvertResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertResp.Marshal(b, m, deterministic)
}
func (m *ConvertResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertResp.Merge(m, src)
}
func (m *ConvertResp) XXX_Size() int {
	return xxx_messageInfo_ConvertResp.Size(m)
}
func (m *ConvertResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertResp proto.InternalMessageInfo

func (m *ConvertResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConvertResp) GetLotteryId() int64 {
	if m != nil {
		return m.LotteryId
	}
	return 0
}

func (m *ConvertResp) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "questions.Request")
	proto.RegisterType((*Response)(nil), "questions.Response")
	proto.RegisterType((*ActivitiesReq)(nil), "questions.ActivitiesReq")
	proto.RegisterType((*ActInfoResp)(nil), "questions.ActInfoResp")
	proto.RegisterType((*AwardInfoResp)(nil), "questions.AwardInfoResp")
	proto.RegisterType((*AwardListResp)(nil), "questions.AwardListResp")
	proto.RegisterType((*QuestionsResp)(nil), "questions.questionsResp")
	proto.RegisterType((*QuestionsListResp)(nil), "questions.QuestionsListResp")
	proto.RegisterType((*QuestionsAnswerReq)(nil), "questions.QuestionsAnswerReq")
	proto.RegisterType((*QuestionsAnswerResp)(nil), "questions.QuestionsAnswerResp")
	proto.RegisterType((*GradeReq)(nil), "questions.GradeReq")
	proto.RegisterType((*TurnTableReq)(nil), "questions.TurnTableReq")
	proto.RegisterType((*ConvertReq)(nil), "questions.ConvertReq")
	proto.RegisterType((*ConvertResp)(nil), "questions.ConvertResp")
}

func init() { proto.RegisterFile("questions.proto", fileDescriptor_8e4cafc9881e02ba) }

var fileDescriptor_8e4cafc9881e02ba = []byte{
	// 829 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0x96, 0xed, 0x64, 0x63, 0xbf, 0xcd, 0xb6, 0xc9, 0x04, 0x82, 0x09, 0x4d, 0x54, 0x59, 0x42,
	0x54, 0x02, 0xf5, 0x50, 0xae, 0x70, 0xd8, 0x06, 0x48, 0x17, 0x55, 0xa2, 0xb8, 0xe1, 0xc4, 0x21,
	0x9a, 0xdd, 0x79, 0x6c, 0x46, 0xda, 0x8c, 0xdd, 0x99, 0x71, 0xab, 0xfc, 0x16, 0x7e, 0x03, 0x37,
	0xc4, 0x6f, 0xe0, 0xc0, 0x85, 0x7f, 0x84, 0x66, 0xc6, 0x1e, 0x8f, 0x37, 0xcd, 0x16, 0x84, 0xa2,
	0xde, 0xe6, 0x7b, 0xef, 0xf9, 0xf3, 0xf7, 0x3e, 0xcf, 0x7b, 0xbb, 0x70, 0xff, 0x55, 0x83, 0x4a,
	0xf3, 0x4a, 0xa8, 0xc7, 0xb5, 0xac, 0x74, 0x45, 0x32, 0x1f, 0x28, 0x8e, 0x61, 0xa7, 0x44, 0x0b,
	0x09, 0x81, 0xad, 0x9a, 0x8b, 0x65, 0x1e, 0x3d, 0x8c, 0x1e, 0x65, 0xa5, 0x3d, 0x17, 0x27, 0x90,
	0x96, 0xa8, 0xea, 0x4a, 0x28, 0xb4, 0xf9, 0x2a, 0xc8, 0x57, 0x62, 0x59, 0x7c, 0x0a, 0x93, 0xe9,
	0x42, 0xf3, 0xd7, 0x5c, 0x73, 0x54, 0x25, 0xbe, 0x22, 0x1f, 0xc0, 0x36, 0x5d, 0x68, 0xce, 0x6c,
	0x55, 0x52, 0x3a, 0x50, 0xfc, 0x11, 0xc3, 0x78, 0xba, 0xd0, 0x33, 0xf1, 0x4b, 0x65, 0xe8, 0xc8,
	0x3d, 0x88, 0x7d, 0x49, 0xcc, 0x99, 0xa1, 0x9e, 0x23, 0x67, 0x79, 0x6c, 0x23, 0xf6, 0x6c, 0x98,
	0x6a, 0x7d, 0xcd, 0x59, 0x9e, 0x38, 0x26, 0x0b, 0x4c, 0x54, 0x73, 0xbd, 0xc2, 0x7c, 0xcb, 0xaa,
	0x70, 0xc0, 0x44, 0x19, 0xaa, 0x85, 0xcc, 0xb7, 0x5d, 0xd4, 0x02, 0x72, 0x08, 0x23, 0xa5, 0xa9,
	0x6e, 0x54, 0x3e, 0xb2, 0x14, 0x2d, 0x22, 0xc7, 0x00, 0x4a, 0x53, 0xa9, 0x2f, 0x18, 0xd5, 0x98,
	0xef, 0xd8, 0x5c, 0x66, 0x23, 0xdf, 0x50, 0x8d, 0xe4, 0x63, 0x48, 0x51, 0x30, 0x97, 0x4c, 0x6d,
	0x72, 0x07, 0x05, 0xb3, 0xa9, 0x4f, 0x20, 0x5b, 0xa2, 0xbe, 0x50, 0x8b, 0x4a, 0x62, 0x9e, 0xd9,
	0x5c, 0xba, 0x44, 0xfd, 0xd2, 0x60, 0xf3, 0xba, 0x4b, 0xa4, 0x0c, 0x65, 0x0e, 0x56, 0x45, 0x8b,
	0xc8, 0x1e, 0x24, 0x0c, 0x55, 0x3e, 0xb6, 0x41, 0x73, 0x34, 0x72, 0xf9, 0x15, 0x5d, 0x62, 0xbe,
	0xeb, 0xe4, 0x5a, 0x60, 0x4c, 0x90, 0xcd, 0x0a, 0xf3, 0x89, 0xf3, 0xd7, 0x9c, 0x8b, 0xdf, 0x62,
	0x98, 0x4c, 0xdf, 0x50, 0xc9, 0xee, 0xcc, 0xba, 0x56, 0xdd, 0x76, 0xaf, 0xee, 0x10, 0x46, 0xa2,
	0xb9, 0x9a, 0xa3, 0xec, 0x6c, 0x73, 0x88, 0x7c, 0x0e, 0xfb, 0xce, 0xb6, 0x5a, 0x56, 0x73, 0x3a,
	0xe7, 0x2b, 0xae, 0xaf, 0x5b, 0xf7, 0xf6, 0x6c, 0xe2, 0x45, 0x1f, 0x27, 0x9f, 0xc1, 0x7d, 0x63,
	0x62, 0x58, 0xea, 0xbc, 0xbc, 0x87, 0x82, 0x85, 0x85, 0x27, 0x00, 0xed, 0x0d, 0xba, 0x9e, 0xb1,
	0xd6, 0xd3, 0x20, 0x72, 0xab, 0xab, 0xde, 0xc3, 0x71, 0xe0, 0x61, 0xf1, 0x75, 0x6b, 0xd7, 0x73,
	0xae, 0xb4, 0xb5, 0xeb, 0x0b, 0xd8, 0x62, 0x54, 0xd3, 0x3c, 0x7a, 0x98, 0x3c, 0x1a, 0x3f, 0xc9,
	0x1f, 0xf7, 0xa3, 0x30, 0xb0, 0xb5, 0xb4, 0x55, 0xc5, 0xdf, 0x11, 0x4c, 0x7c, 0xc5, 0xff, 0xb4,
	0x3b, 0x87, 0x9d, 0x1f, 0x6a, 0x4b, 0xd4, 0x1a, 0xde, 0x41, 0x93, 0x39, 0xad, 0xa4, 0x44, 0xa1,
	0x5b, 0xdb, 0x3b, 0x68, 0x9a, 0x7d, 0x39, 0xb8, 0xb1, 0x0e, 0x91, 0x23, 0x48, 0x7f, 0x6c, 0x65,
	0x59, 0xc7, 0xb3, 0xd2, 0xe3, 0x35, 0x03, 0xd3, 0x75, 0x03, 0x8b, 0x29, 0xec, 0x77, 0xb5, 0xea,
	0x5f, 0xd8, 0x32, 0x68, 0xbf, 0xb5, 0xe5, 0xf7, 0x08, 0x88, 0xe7, 0x98, 0x0a, 0xf5, 0x06, 0xa5,
	0x99, 0xf5, 0xce, 0x8b, 0xe8, 0x6d, 0x5e, 0xc4, 0xa1, 0x17, 0x43, 0x8d, 0xc9, 0x8d, 0x8f, 0xbc,
	0x07, 0xc9, 0x4f, 0x9c, 0x59, 0x9f, 0x92, 0xd2, 0x1c, 0x8d, 0x47, 0xd4, 0xbe, 0xa8, 0xbb, 0x9a,
	0x1d, 0x34, 0x6f, 0x70, 0xf3, 0x37, 0x72, 0x1f, 0xde, 0x02, 0xa3, 0x65, 0xda, 0x70, 0xd6, 0xde,
	0x47, 0x7b, 0x2e, 0x9e, 0xc1, 0xc1, 0x0d, 0xd5, 0xaa, 0x36, 0x43, 0xec, 0xb8, 0x2e, 0xbc, 0xf6,
	0xd4, 0x05, 0x66, 0xac, 0x67, 0x8f, 0x03, 0xf6, 0xe2, 0x3b, 0x48, 0xcf, 0x24, 0x65, 0x78, 0xeb,
	0x86, 0x33, 0x1d, 0x34, 0xbe, 0x6b, 0x73, 0xf4, 0x8a, 0x92, 0x40, 0xd1, 0xaf, 0x11, 0xec, 0x9e,
	0x37, 0x52, 0x9c, 0xd3, 0xf9, 0x0a, 0xef, 0xda, 0xc2, 0x4e, 0xc0, 0x76, 0x2f, 0x60, 0xd8, 0xfb,
	0x68, 0xd8, 0x7b, 0xf1, 0x57, 0x04, 0x70, 0x5a, 0x89, 0xd7, 0x28, 0xf5, 0xfb, 0xd0, 0xf6, 0x00,
	0xb2, 0xe7, 0x95, 0xd6, 0x28, 0x0d, 0x89, 0xd3, 0xd6, 0x07, 0xcc, 0x08, 0x34, 0x0a, 0xa5, 0xa0,
	0x57, 0xd8, 0x8d, 0x40, 0x87, 0xad, 0xaa, 0xcb, 0x4a, 0xb8, 0x75, 0x9d, 0x95, 0x0e, 0x14, 0x3f,
	0xc3, 0xd8, 0x77, 0xe3, 0x26, 0x79, 0xe6, 0x27, 0x79, 0xb6, 0xf6, 0xba, 0x78, 0xfd, 0x75, 0xef,
	0x68, 0xe9, 0xc9, 0x9f, 0x5b, 0x90, 0xf9, 0xcb, 0x45, 0xbe, 0x85, 0xfd, 0x33, 0xd4, 0xfd, 0x2f,
	0xa1, 0x59, 0x2b, 0x64, 0xb0, 0x6c, 0xc2, 0x1f, 0xc9, 0xa3, 0xc3, 0x61, 0xc6, 0xef, 0xf6, 0xa7,
	0xb0, 0x6b, 0x68, 0xba, 0xc5, 0xb4, 0x81, 0xe1, 0xd6, 0x45, 0x16, 0x72, 0x98, 0x69, 0xff, 0x2f,
	0x1c, 0x7e, 0x3b, 0x7c, 0x0f, 0x7b, 0x67, 0xa8, 0x07, 0x5b, 0x63, 0x03, 0xcf, 0x83, 0x20, 0x73,
	0x73, 0xd3, 0x9c, 0xc3, 0xc1, 0x8b, 0x4a, 0xf5, 0x64, 0xa7, 0x97, 0x54, 0x2c, 0x91, 0x1c, 0xbf,
	0xed, 0x21, 0xbf, 0x5a, 0x8e, 0x4e, 0x36, 0xa5, 0x55, 0x4d, 0x9e, 0x59, 0xc3, 0x7d, 0xc6, 0x0e,
	0x27, 0x39, 0x08, 0x1e, 0xea, 0xc6, 0xf5, 0x9d, 0x4c, 0x4f, 0x61, 0x62, 0xf4, 0xf9, 0xa9, 0x24,
	0x1f, 0x05, 0x0f, 0x84, 0xb3, 0xba, 0xc1, 0xf3, 0xaf, 0x60, 0x6c, 0x38, 0xda, 0xdb, 0x46, 0x3e,
	0x0c, 0x0a, 0xfb, 0x79, 0x1a, 0x7c, 0xf5, 0xe0, 0x62, 0xce, 0x47, 0xf6, 0x4f, 0xd9, 0x97, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xed, 0x03, 0xbc, 0xa7, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuestionsClient is the client API for Questions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuestionsClient interface {
	//获取 问答抽奖活动信息
	GetActivitiesInfo(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*ActInfoResp, error)
	//获取 问答奖品信息
	GetAwardInfo(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*AwardInfoResp, error)
	//获取 问答奖品列表
	GetAwardList(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*AwardListResp, error)
	//获取 问题列表
	GetQuestionsList(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*QuestionsListResp, error)
	// 提交 答案
	PostQuestionsChange(ctx context.Context, in *QuestionsAnswerReq, opts ...grpc.CallOption) (*QuestionsAnswerResp, error)
	//获取得分
	GetQuestionsGrade(ctx context.Context, in *GradeReq, opts ...grpc.CallOption) (*QuestionsAnswerResp, error)
	//抽奖
	PostTurnTable(ctx context.Context, in *TurnTableReq, opts ...grpc.CallOption) (*AwardInfoResp, error)
	//填写中奖记录
	PostConvert(ctx context.Context, in *ConvertReq, opts ...grpc.CallOption) (*ConvertResp, error)
}

type questionsClient struct {
	cc *grpc.ClientConn
}

func NewQuestionsClient(cc *grpc.ClientConn) QuestionsClient {
	return &questionsClient{cc}
}

func (c *questionsClient) GetActivitiesInfo(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*ActInfoResp, error) {
	out := new(ActInfoResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/GetActivitiesInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) GetAwardInfo(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*AwardInfoResp, error) {
	out := new(AwardInfoResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/GetAwardInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) GetAwardList(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*AwardListResp, error) {
	out := new(AwardListResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/GetAwardList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) GetQuestionsList(ctx context.Context, in *ActivitiesReq, opts ...grpc.CallOption) (*QuestionsListResp, error) {
	out := new(QuestionsListResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/GetQuestionsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) PostQuestionsChange(ctx context.Context, in *QuestionsAnswerReq, opts ...grpc.CallOption) (*QuestionsAnswerResp, error) {
	out := new(QuestionsAnswerResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/PostQuestionsChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) GetQuestionsGrade(ctx context.Context, in *GradeReq, opts ...grpc.CallOption) (*QuestionsAnswerResp, error) {
	out := new(QuestionsAnswerResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/GetQuestionsGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) PostTurnTable(ctx context.Context, in *TurnTableReq, opts ...grpc.CallOption) (*AwardInfoResp, error) {
	out := new(AwardInfoResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/PostTurnTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionsClient) PostConvert(ctx context.Context, in *ConvertReq, opts ...grpc.CallOption) (*ConvertResp, error) {
	out := new(ConvertResp)
	err := c.cc.Invoke(ctx, "/questions.Questions/PostConvert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionsServer is the server API for Questions service.
type QuestionsServer interface {
	//获取 问答抽奖活动信息
	GetActivitiesInfo(context.Context, *ActivitiesReq) (*ActInfoResp, error)
	//获取 问答奖品信息
	GetAwardInfo(context.Context, *ActivitiesReq) (*AwardInfoResp, error)
	//获取 问答奖品列表
	GetAwardList(context.Context, *ActivitiesReq) (*AwardListResp, error)
	//获取 问题列表
	GetQuestionsList(context.Context, *ActivitiesReq) (*QuestionsListResp, error)
	// 提交 答案
	PostQuestionsChange(context.Context, *QuestionsAnswerReq) (*QuestionsAnswerResp, error)
	//获取得分
	GetQuestionsGrade(context.Context, *GradeReq) (*QuestionsAnswerResp, error)
	//抽奖
	PostTurnTable(context.Context, *TurnTableReq) (*AwardInfoResp, error)
	//填写中奖记录
	PostConvert(context.Context, *ConvertReq) (*ConvertResp, error)
}

// UnimplementedQuestionsServer can be embedded to have forward compatible implementations.
type UnimplementedQuestionsServer struct {
}

func (*UnimplementedQuestionsServer) GetActivitiesInfo(ctx context.Context, req *ActivitiesReq) (*ActInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivitiesInfo not implemented")
}
func (*UnimplementedQuestionsServer) GetAwardInfo(ctx context.Context, req *ActivitiesReq) (*AwardInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAwardInfo not implemented")
}
func (*UnimplementedQuestionsServer) GetAwardList(ctx context.Context, req *ActivitiesReq) (*AwardListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAwardList not implemented")
}
func (*UnimplementedQuestionsServer) GetQuestionsList(ctx context.Context, req *ActivitiesReq) (*QuestionsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsList not implemented")
}
func (*UnimplementedQuestionsServer) PostQuestionsChange(ctx context.Context, req *QuestionsAnswerReq) (*QuestionsAnswerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostQuestionsChange not implemented")
}
func (*UnimplementedQuestionsServer) GetQuestionsGrade(ctx context.Context, req *GradeReq) (*QuestionsAnswerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsGrade not implemented")
}
func (*UnimplementedQuestionsServer) PostTurnTable(ctx context.Context, req *TurnTableReq) (*AwardInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTurnTable not implemented")
}
func (*UnimplementedQuestionsServer) PostConvert(ctx context.Context, req *ConvertReq) (*ConvertResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostConvert not implemented")
}

func RegisterQuestionsServer(s *grpc.Server, srv QuestionsServer) {
	s.RegisterService(&_Questions_serviceDesc, srv)
}

func _Questions_GetActivitiesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).GetActivitiesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/GetActivitiesInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).GetActivitiesInfo(ctx, req.(*ActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_GetAwardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).GetAwardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/GetAwardInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).GetAwardInfo(ctx, req.(*ActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_GetAwardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).GetAwardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/GetAwardList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).GetAwardList(ctx, req.(*ActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_GetQuestionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).GetQuestionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/GetQuestionsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).GetQuestionsList(ctx, req.(*ActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_PostQuestionsChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionsAnswerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).PostQuestionsChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/PostQuestionsChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).PostQuestionsChange(ctx, req.(*QuestionsAnswerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_GetQuestionsGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).GetQuestionsGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/GetQuestionsGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).GetQuestionsGrade(ctx, req.(*GradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_PostTurnTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).PostTurnTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/PostTurnTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).PostTurnTable(ctx, req.(*TurnTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Questions_PostConvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServer).PostConvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questions.Questions/PostConvert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServer).PostConvert(ctx, req.(*ConvertReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Questions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "questions.Questions",
	HandlerType: (*QuestionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivitiesInfo",
			Handler:    _Questions_GetActivitiesInfo_Handler,
		},
		{
			MethodName: "GetAwardInfo",
			Handler:    _Questions_GetAwardInfo_Handler,
		},
		{
			MethodName: "GetAwardList",
			Handler:    _Questions_GetAwardList_Handler,
		},
		{
			MethodName: "GetQuestionsList",
			Handler:    _Questions_GetQuestionsList_Handler,
		},
		{
			MethodName: "PostQuestionsChange",
			Handler:    _Questions_PostQuestionsChange_Handler,
		},
		{
			MethodName: "GetQuestionsGrade",
			Handler:    _Questions_GetQuestionsGrade_Handler,
		},
		{
			MethodName: "PostTurnTable",
			Handler:    _Questions_PostTurnTable_Handler,
		},
		{
			MethodName: "PostConvert",
			Handler:    _Questions_PostConvert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "questions.proto",
}
