// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LimitReq struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitReq) Reset()         { *m = LimitReq{} }
func (m *LimitReq) String() string { return proto.CompactTextString(m) }
func (*LimitReq) ProtoMessage()    {}
func (*LimitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *LimitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitReq.Unmarshal(m, b)
}
func (m *LimitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitReq.Marshal(b, m, deterministic)
}
func (m *LimitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitReq.Merge(m, src)
}
func (m *LimitReq) XXX_Size() int {
	return xxx_messageInfo_LimitReq.Size(m)
}
func (m *LimitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitReq.DiscardUnknown(m)
}

var xxx_messageInfo_LimitReq proto.InternalMessageInfo

func (m *LimitReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *LimitReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SearchReq struct {
	Keyword              string    `protobuf:"bytes,1,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	Limit                *LimitReq `protobuf:"bytes,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchReq) GetLimit() *LimitReq {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ArticleResp struct {
	List                 []*ArticleReq `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ArticleResp) Reset()         { *m = ArticleResp{} }
func (m *ArticleResp) String() string { return proto.CompactTextString(m) }
func (*ArticleResp) ProtoMessage()    {}
func (*ArticleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *ArticleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResp.Unmarshal(m, b)
}
func (m *ArticleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResp.Marshal(b, m, deterministic)
}
func (m *ArticleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResp.Merge(m, src)
}
func (m *ArticleResp) XXX_Size() int {
	return xxx_messageInfo_ArticleResp.Size(m)
}
func (m *ArticleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResp.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResp proto.InternalMessageInfo

func (m *ArticleResp) GetList() []*ArticleReq {
	if m != nil {
		return m.List
	}
	return nil
}

type ArticleReq struct {
	NewsId               string   `protobuf:"bytes,1,opt,name=NewsId,proto3" json:"NewsId,omitempty"`
	NewsTitle            string   `protobuf:"bytes,2,opt,name=NewsTitle,proto3" json:"NewsTitle,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleReq) Reset()         { *m = ArticleReq{} }
func (m *ArticleReq) String() string { return proto.CompactTextString(m) }
func (*ArticleReq) ProtoMessage()    {}
func (*ArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *ArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleReq.Unmarshal(m, b)
}
func (m *ArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleReq.Marshal(b, m, deterministic)
}
func (m *ArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleReq.Merge(m, src)
}
func (m *ArticleReq) XXX_Size() int {
	return xxx_messageInfo_ArticleReq.Size(m)
}
func (m *ArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleReq proto.InternalMessageInfo

func (m *ArticleReq) GetNewsId() string {
	if m != nil {
		return m.NewsId
	}
	return ""
}

func (m *ArticleReq) GetNewsTitle() string {
	if m != nil {
		return m.NewsTitle
	}
	return ""
}

func (m *ArticleReq) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type Request struct {
	Once                 bool     `protobuf:"varint,1,opt,name=Once,proto3" json:"Once,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOnce() bool {
	if m != nil {
		return m.Once
	}
	return false
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LimitReq)(nil), "search.LimitReq")
	proto.RegisterType((*SearchReq)(nil), "search.SearchReq")
	proto.RegisterType((*ArticleResp)(nil), "search.ArticleResp")
	proto.RegisterType((*ArticleReq)(nil), "search.ArticleReq")
	proto.RegisterType((*Request)(nil), "search.Request")
	proto.RegisterType((*Response)(nil), "search.Response")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x83, 0x60, 0x69, 0x07, 0x8c, 0x38, 0x26, 0xa6, 0x21, 0x9a, 0x98, 0x3d, 0x10, 0x4e,
	0xc4, 0xe0, 0xbf, 0xb3, 0x47, 0x22, 0x6a, 0xb2, 0xe8, 0xd5, 0x04, 0x71, 0xd0, 0x4d, 0x80, 0x6d,
	0x77, 0xd7, 0x10, 0xfd, 0x46, 0x7e, 0x4b, 0xd3, 0xd9, 0x6e, 0x7b, 0x90, 0xdb, 0xbc, 0x99, 0xfd,
	0xbd, 0x7d, 0xb3, 0x2d, 0x74, 0x2d, 0xcd, 0xcd, 0xe2, 0x73, 0x94, 0x19, 0xed, 0x34, 0x46, 0x5e,
	0x89, 0x1b, 0x88, 0xa7, 0x6a, 0xad, 0x9c, 0xa4, 0x1c, 0x4f, 0x20, 0xd2, 0xcb, 0xa5, 0x25, 0x97,
	0x36, 0xce, 0x1b, 0xc3, 0xa6, 0x2c, 0x15, 0x22, 0xb4, 0xac, 0xfa, 0xa1, 0x74, 0x8f, 0xbb, 0x5c,
	0x8b, 0x07, 0x48, 0x66, 0xec, 0x50, 0x80, 0x29, 0xb4, 0xef, 0xe9, 0x7b, 0xab, 0xcd, 0x3b, 0x93,
	0x89, 0x0c, 0x12, 0x07, 0xb0, 0xcf, 0xf6, 0xcc, 0x76, 0xc6, 0xbd, 0x51, 0x19, 0x22, 0xdc, 0x29,
	0xfd, 0x58, 0x5c, 0x43, 0xe7, 0xce, 0x38, 0xb5, 0x58, 0x91, 0x24, 0x9b, 0xe1, 0x00, 0x5a, 0x53,
	0x65, 0x8b, 0x1c, 0xcd, 0x61, 0x67, 0x8c, 0x81, 0xaa, 0x8e, 0xe4, 0x92, 0xe7, 0xe2, 0x15, 0xa0,
	0xee, 0x15, 0xf9, 0x1f, 0x69, 0x6b, 0x27, 0x21, 0x45, 0xa9, 0xf0, 0x14, 0x92, 0xa2, 0x7a, 0x56,
	0x6e, 0xe5, 0x97, 0x48, 0x64, 0xdd, 0xc0, 0x3e, 0xc4, 0x93, 0xf5, 0xfc, 0x83, 0x5e, 0xcc, 0x2a,
	0x6d, 0xf2, 0xb0, 0xd2, 0xe2, 0x0c, 0xda, 0x92, 0xf2, 0x2f, 0xb2, 0xfc, 0x08, 0x4f, 0x9b, 0x05,
	0xb1, 0x75, 0x2c, 0xb9, 0x16, 0x00, 0x71, 0x11, 0x57, 0x6f, 0x2c, 0x8d, 0x7f, 0x1b, 0x10, 0xf9,
	0x17, 0xc1, 0x8b, 0x6a, 0x99, 0xc9, 0x46, 0x39, 0x3c, 0x0c, 0xf1, 0x4b, 0xab, 0x7e, 0xaf, 0x6e,
	0x78, 0x18, 0xaf, 0xa0, 0x5b, 0x12, 0x33, 0xa7, 0x0d, 0xe1, 0x8e, 0x8d, 0x77, 0x50, 0xb7, 0x70,
	0x10, 0x28, 0x7f, 0xf1, 0x51, 0x38, 0x52, 0x7d, 0x9a, 0xfe, 0xf1, 0x3f, 0x27, 0x9b, 0xbd, 0x45,
	0xfc, 0x0f, 0x5c, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xd4, 0xf6, 0x9c, 0x13, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	ArticleInit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ArticleStore(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*Response, error)
	ArticleSearch(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*ArticleResp, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) ArticleInit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/search.Search/ArticleInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ArticleStore(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/search.Search/ArticleStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ArticleSearch(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/search.Search/ArticleSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	ArticleInit(context.Context, *Request) (*Response, error)
	ArticleStore(context.Context, *ArticleReq) (*Response, error)
	ArticleSearch(context.Context, *SearchReq) (*ArticleResp, error)
}

// UnimplementedSearchServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (*UnimplementedSearchServer) ArticleInit(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleInit not implemented")
}
func (*UnimplementedSearchServer) ArticleStore(ctx context.Context, req *ArticleReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleStore not implemented")
}
func (*UnimplementedSearchServer) ArticleSearch(ctx context.Context, req *SearchReq) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleSearch not implemented")
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_ArticleInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ArticleInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/ArticleInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ArticleInit(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ArticleStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ArticleStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/ArticleStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ArticleStore(ctx, req.(*ArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ArticleSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ArticleSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/ArticleSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ArticleSearch(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArticleInit",
			Handler:    _Search_ArticleInit_Handler,
		},
		{
			MethodName: "ArticleStore",
			Handler:    _Search_ArticleStore_Handler,
		},
		{
			MethodName: "ArticleSearch",
			Handler:    _Search_ArticleSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
