// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

//注册请求
type RegisterReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Smscode              string   `protobuf:"bytes,3,opt,name=smscode,proto3" json:"smscode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetSmscode() string {
	if m != nil {
		return m.Smscode
	}
	return ""
}

//登陆请求
type LoginReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginReq) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//返回用户信息
type UserReply struct {
	Auid                 int64     `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Uid                  int64     `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Beid                 int64     `protobuf:"varint,3,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64     `protobuf:"varint,4,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Username             string    `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Mobile               string    `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname             string    `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Openid               string    `protobuf:"bytes,8,opt,name=openid,proto3" json:"openid,omitempty"`
	Avator               string    `protobuf:"bytes,9,opt,name=avator,proto3" json:"avator,omitempty"`
	Jwttoken             *JwtToken `protobuf:"bytes,10,opt,name=jwttoken,proto3" json:"jwttoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserReply) Reset()         { *m = UserReply{} }
func (m *UserReply) String() string { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()    {}
func (*UserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReply.Unmarshal(m, b)
}
func (m *UserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReply.Marshal(b, m, deterministic)
}
func (m *UserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReply.Merge(m, src)
}
func (m *UserReply) XXX_Size() int {
	return xxx_messageInfo_UserReply.Size(m)
}
func (m *UserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserReply proto.InternalMessageInfo

func (m *UserReply) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *UserReply) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserReply) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *UserReply) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *UserReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserReply) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserReply) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserReply) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *UserReply) GetAvator() string {
	if m != nil {
		return m.Avator
	}
	return ""
}

func (m *UserReply) GetJwttoken() *JwtToken {
	if m != nil {
		return m.Jwttoken
	}
	return nil
}

//返回用户信息
type UserReq struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Beid                 int64    `protobuf:"varint,3,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,4,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *UserReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *UserReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

type JwtToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,3,opt,name=refreshAfter,proto3" json:"refreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtToken) Reset()         { *m = JwtToken{} }
func (m *JwtToken) String() string { return proto.CompactTextString(m) }
func (*JwtToken) ProtoMessage()    {}
func (*JwtToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *JwtToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtToken.Unmarshal(m, b)
}
func (m *JwtToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtToken.Marshal(b, m, deterministic)
}
func (m *JwtToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtToken.Merge(m, src)
}
func (m *JwtToken) XXX_Size() int {
	return xxx_messageInfo_JwtToken.Size(m)
}
func (m *JwtToken) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtToken.DiscardUnknown(m)
}

var xxx_messageInfo_JwtToken proto.InternalMessageInfo

func (m *JwtToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *JwtToken) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *JwtToken) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

//请求的api
type AppConfigReq struct {
	Beid                 int64    `protobuf:"varint,1,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,2,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfigReq) Reset()         { *m = AppConfigReq{} }
func (m *AppConfigReq) String() string { return proto.CompactTextString(m) }
func (*AppConfigReq) ProtoMessage()    {}
func (*AppConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *AppConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfigReq.Unmarshal(m, b)
}
func (m *AppConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfigReq.Marshal(b, m, deterministic)
}
func (m *AppConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfigReq.Merge(m, src)
}
func (m *AppConfigReq) XXX_Size() int {
	return xxx_messageInfo_AppConfigReq.Size(m)
}
func (m *AppConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfigReq proto.InternalMessageInfo

func (m *AppConfigReq) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *AppConfigReq) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *AppConfigReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

//返回用户的信息
type AppUserResp struct {
	Auid                 int64    `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avator               string   `protobuf:"bytes,5,opt,name=avator,proto3" json:"avator,omitempty"`
	Openid               string   `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Sex                  int64    `protobuf:"varint,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Unionid              string   `protobuf:"bytes,11,opt,name=unionid,proto3" json:"unionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppUserResp) Reset()         { *m = AppUserResp{} }
func (m *AppUserResp) String() string { return proto.CompactTextString(m) }
func (*AppUserResp) ProtoMessage()    {}
func (*AppUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *AppUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppUserResp.Unmarshal(m, b)
}
func (m *AppUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppUserResp.Marshal(b, m, deterministic)
}
func (m *AppUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppUserResp.Merge(m, src)
}
func (m *AppUserResp) XXX_Size() int {
	return xxx_messageInfo_AppUserResp.Size(m)
}
func (m *AppUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppUserResp proto.InternalMessageInfo

func (m *AppUserResp) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *AppUserResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *AppUserResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *AppUserResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AppUserResp) GetAvator() string {
	if m != nil {
		return m.Avator
	}
	return ""
}

func (m *AppUserResp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *AppUserResp) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AppUserResp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AppUserResp) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AppUserResp) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *AppUserResp) GetUnionid() string {
	if m != nil {
		return m.Unionid
	}
	return ""
}

type AppUserLoginResp struct {
	Auid                 int64     `protobuf:"varint,1,opt,name=auid,proto3" json:"auid,omitempty"`
	Beid                 int64     `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64     `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Nickname             string    `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avator               string    `protobuf:"bytes,5,opt,name=avator,proto3" json:"avator,omitempty"`
	Openid               string    `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`
	Province             string    `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City                 string    `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Country              string    `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Sex                  string    `protobuf:"bytes,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Jwttoken             *JwtToken `protobuf:"bytes,11,opt,name=jwttoken,proto3" json:"jwttoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppUserLoginResp) Reset()         { *m = AppUserLoginResp{} }
func (m *AppUserLoginResp) String() string { return proto.CompactTextString(m) }
func (*AppUserLoginResp) ProtoMessage()    {}
func (*AppUserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *AppUserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppUserLoginResp.Unmarshal(m, b)
}
func (m *AppUserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppUserLoginResp.Marshal(b, m, deterministic)
}
func (m *AppUserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppUserLoginResp.Merge(m, src)
}
func (m *AppUserLoginResp) XXX_Size() int {
	return xxx_messageInfo_AppUserLoginResp.Size(m)
}
func (m *AppUserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppUserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppUserLoginResp proto.InternalMessageInfo

func (m *AppUserLoginResp) GetAuid() int64 {
	if m != nil {
		return m.Auid
	}
	return 0
}

func (m *AppUserLoginResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *AppUserLoginResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *AppUserLoginResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AppUserLoginResp) GetAvator() string {
	if m != nil {
		return m.Avator
	}
	return ""
}

func (m *AppUserLoginResp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *AppUserLoginResp) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AppUserLoginResp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AppUserLoginResp) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AppUserLoginResp) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *AppUserLoginResp) GetJwttoken() *JwtToken {
	if m != nil {
		return m.Jwttoken
	}
	return nil
}

//返回的值
type AppConfigResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Beid                 int64    `protobuf:"varint,2,opt,name=beid,proto3" json:"beid,omitempty"`
	Ptyid                int64    `protobuf:"varint,3,opt,name=ptyid,proto3" json:"ptyid,omitempty"`
	Appid                string   `protobuf:"bytes,4,opt,name=appid,proto3" json:"appid,omitempty"`
	Appsecret            string   `protobuf:"bytes,5,opt,name=appsecret,proto3" json:"appsecret,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfigResp) Reset()         { *m = AppConfigResp{} }
func (m *AppConfigResp) String() string { return proto.CompactTextString(m) }
func (*AppConfigResp) ProtoMessage()    {}
func (*AppConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *AppConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfigResp.Unmarshal(m, b)
}
func (m *AppConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfigResp.Marshal(b, m, deterministic)
}
func (m *AppConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfigResp.Merge(m, src)
}
func (m *AppConfigResp) XXX_Size() int {
	return xxx_messageInfo_AppConfigResp.Size(m)
}
func (m *AppConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfigResp proto.InternalMessageInfo

func (m *AppConfigResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppConfigResp) GetBeid() int64 {
	if m != nil {
		return m.Beid
	}
	return 0
}

func (m *AppConfigResp) GetPtyid() int64 {
	if m != nil {
		return m.Ptyid
	}
	return 0
}

func (m *AppConfigResp) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AppConfigResp) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

func (m *AppConfigResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Response struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
	proto.RegisterType((*LoginReq)(nil), "user.LoginReq")
	proto.RegisterType((*UserReply)(nil), "user.UserReply")
	proto.RegisterType((*UserReq)(nil), "user.UserReq")
	proto.RegisterType((*JwtToken)(nil), "user.JwtToken")
	proto.RegisterType((*AppConfigReq)(nil), "user.AppConfigReq")
	proto.RegisterType((*AppUserResp)(nil), "user.AppUserResp")
	proto.RegisterType((*AppUserLoginResp)(nil), "user.AppUserLoginResp")
	proto.RegisterType((*AppConfigResp)(nil), "user.AppConfigResp")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xff, 0x24, 0xb1, 0xc7, 0x6d, 0x7f, 0xed, 0xaa, 0xfa, 0xc9, 0x8a, 0x00, 0x55, 0x96,
	0x90, 0xaa, 0x1e, 0x2a, 0x51, 0x9e, 0x20, 0x42, 0x1c, 0x40, 0x3d, 0x20, 0x03, 0x07, 0xc4, 0xc9,
	0x71, 0x36, 0x66, 0x69, 0xb3, 0xbb, 0xd9, 0xdd, 0x34, 0xcd, 0x13, 0x70, 0xe2, 0xc4, 0x2b, 0xf0,
	0x6c, 0x3c, 0x07, 0xda, 0x7f, 0x8e, 0xdd, 0x44, 0x20, 0x24, 0x4e, 0xdc, 0xe6, 0x9b, 0x9d, 0x9d,
	0x59, 0x7f, 0xdf, 0xcc, 0x18, 0x60, 0x25, 0xb1, 0xb8, 0xe4, 0x82, 0x29, 0x86, 0x62, 0x6d, 0x17,
	0x8f, 0x61, 0x54, 0xe2, 0xe5, 0x0a, 0x4b, 0x85, 0x10, 0xc4, 0x9c, 0xd0, 0x26, 0x0f, 0xce, 0x82,
	0xf3, 0xb4, 0x34, 0x76, 0xf1, 0x11, 0xb2, 0x12, 0x37, 0x44, 0x2a, 0x2c, 0x4a, 0xbc, 0x44, 0xff,
	0xc3, 0x70, 0xc1, 0xa6, 0xe4, 0x16, 0xbb, 0x20, 0x87, 0xd0, 0x18, 0x12, 0x5e, 0x49, 0xb9, 0x66,
	0x62, 0x96, 0x87, 0xe6, 0xa4, 0xc5, 0x28, 0x87, 0x91, 0x5c, 0xc8, 0x9a, 0xcd, 0x70, 0x1e, 0x99,
	0x23, 0x0f, 0x8b, 0x12, 0x92, 0x6b, 0xd6, 0x10, 0xfa, 0xab, 0xcc, 0x08, 0x62, 0xb5, 0xe1, 0xd8,
	0x64, 0x8d, 0x4a, 0x63, 0xf7, 0xaa, 0x45, 0xfd, 0x6a, 0xc5, 0x97, 0x10, 0xd2, 0xf7, 0x52, 0xbf,
	0x96, 0xdf, 0x6e, 0xf4, 0xed, 0x6a, 0x45, 0x66, 0x26, 0x67, 0x54, 0x1a, 0x1b, 0x1d, 0x43, 0xa4,
	0x5d, 0x36, 0xa1, 0x36, 0x75, 0xd4, 0x14, 0x13, 0x9b, 0x2b, 0x2a, 0x8d, 0x8d, 0x4e, 0x61, 0xc0,
	0xd5, 0x86, 0xcc, 0xf2, 0xd8, 0x38, 0x2d, 0xd0, 0x95, 0x35, 0x6b, 0xb4, 0x5a, 0xe0, 0x7c, 0x60,
	0x2b, 0x7b, 0xdc, 0xf9, 0x82, 0xe1, 0x43, 0x6e, 0x28, 0xa9, 0x6f, 0xcc, 0x9d, 0x91, 0xbd, 0xe3,
	0xb1, 0xbe, 0xc3, 0x38, 0xa6, 0x64, 0x96, 0x27, 0xf6, 0x8e, 0x45, 0xda, 0x5f, 0xdd, 0x55, 0x8a,
	0x89, 0x3c, 0xb5, 0x7e, 0x8b, 0xd0, 0x05, 0x24, 0x9f, 0xd7, 0x4a, 0xb1, 0x1b, 0x4c, 0x73, 0x38,
	0x0b, 0xce, 0xb3, 0xab, 0xa3, 0x4b, 0x23, 0xe9, 0xeb, 0xb5, 0x7a, 0xa7, 0xbd, 0x65, 0x7b, 0x5e,
	0x7c, 0x80, 0x91, 0x25, 0x62, 0xf9, 0xb7, 0x69, 0x28, 0x14, 0x24, 0xbe, 0x20, 0x3a, 0x83, 0xac,
	0xaa, 0x6b, 0x2c, 0xa5, 0x81, 0x4e, 0xbd, 0xae, 0x0b, 0x15, 0x70, 0x60, 0xe1, 0xcb, 0x7b, 0x4e,
	0x84, 0x97, 0xb2, 0xe7, 0xd3, 0x31, 0x02, 0xcf, 0x05, 0x96, 0x9f, 0x26, 0x73, 0x85, 0x85, 0x7b,
	0x43, 0xcf, 0x57, 0x5c, 0xc3, 0xc1, 0x84, 0xf3, 0x17, 0x8c, 0xce, 0x49, 0xe3, 0xbe, 0xca, 0xbc,
	0x37, 0xd8, 0xf7, 0xde, 0xb0, 0x2b, 0x1b, 0x82, 0xb8, 0xd3, 0x7f, 0xc6, 0x2e, 0xbe, 0x86, 0x90,
	0x4d, 0x38, 0xb7, 0x14, 0x49, 0xbe, 0x97, 0x23, 0x5f, 0x21, 0xdc, 0x57, 0x21, 0x7a, 0xd0, 0x18,
	0xad, 0xc8, 0xf1, 0xae, 0xc8, 0x4e, 0xcc, 0x41, 0x4f, 0xcc, 0xad, 0xf8, 0xc3, 0x9e, 0xf8, 0xba,
	0xbd, 0x05, 0xbb, 0x23, 0xb4, 0x6e, 0x1b, 0xc6, 0x63, 0xf3, 0x25, 0x44, 0x6d, 0x5c, 0xbb, 0x18,
	0x5b, 0x0f, 0x58, 0xcd, 0x56, 0x54, 0x89, 0x8d, 0xeb, 0x16, 0x0f, 0xb5, 0xc6, 0x12, 0xdf, 0x9b,
	0x4e, 0x89, 0x4a, 0x6d, 0xea, 0xd8, 0x15, 0x25, 0x4c, 0x17, 0xcd, 0x6c, 0xac, 0x83, 0xc5, 0xf7,
	0x10, 0x8e, 0x1d, 0x1f, 0x6e, 0x28, 0xff, 0x7d, 0x52, 0x52, 0x4b, 0x4a, 0x77, 0xaa, 0xb2, 0xdf,
	0x4c, 0xd5, 0xb7, 0x00, 0x0e, 0x3b, 0x5d, 0x28, 0x39, 0x3a, 0x82, 0xb0, 0x65, 0x28, 0xfc, 0x23,
	0x7e, 0x4e, 0x61, 0x50, 0x71, 0xee, 0x86, 0x2b, 0x2d, 0x2d, 0x40, 0x8f, 0x20, 0xad, 0x38, 0x97,
	0xb8, 0x16, 0x58, 0x39, 0x72, 0xb6, 0x0e, 0x7d, 0x47, 0x11, 0xd5, 0x2e, 0x19, 0x0b, 0x8a, 0x27,
	0x90, 0xe8, 0xb7, 0x30, 0x2a, 0x0d, 0x1b, 0x9c, 0x75, 0xd6, 0x38, 0xa3, 0xcd, 0xd5, 0x8f, 0x00,
	0x62, 0xad, 0x2c, 0x7a, 0x0a, 0xf1, 0x1b, 0x42, 0x1b, 0x74, 0x68, 0x3f, 0xd0, 0xad, 0xfe, 0xf1,
	0x91, 0x87, 0x2e, 0xc7, 0xa5, 0xce, 0x67, 0xd7, 0x3e, 0x3a, 0xf1, 0x67, 0xed, 0x6f, 0x60, 0xfc,
	0x9f, 0x75, 0x6d, 0xf7, 0xec, 0x39, 0x0c, 0x4c, 0xd3, 0x20, 0x97, 0xc8, 0xaf, 0xf5, 0xdd, 0xc8,
	0x0b, 0x48, 0x34, 0x78, 0x45, 0xe7, 0xcc, 0x3f, 0xc2, 0x6d, 0xa9, 0xdd, 0xd8, 0x67, 0x90, 0xbc,
	0xa5, 0xd2, 0x26, 0x46, 0xf6, 0xb0, 0xbb, 0x00, 0xc6, 0x27, 0xad, 0xcf, 0x4f, 0xf1, 0x74, 0x68,
	0xfe, 0x6d, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xa0, 0x0e, 0xf9, 0xe9, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*UserReply, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*UserReply, error)
	UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error)
	SnsLogin(ctx context.Context, in *AppConfigReq, opts ...grpc.CallOption) (*AppUserResp, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.User/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/user.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/user.User/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/user.User/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SnsLogin(ctx context.Context, in *AppConfigReq, opts ...grpc.CallOption) (*AppUserResp, error) {
	out := new(AppUserResp)
	err := c.cc.Invoke(ctx, "/user.User/SnsLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Register(context.Context, *RegisterReq) (*UserReply, error)
	Login(context.Context, *LoginReq) (*UserReply, error)
	UserInfo(context.Context, *UserReq) (*UserReply, error)
	SnsLogin(context.Context, *AppConfigReq) (*AppUserResp, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Ping(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterReq) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginReq) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) UserInfo(ctx context.Context, req *UserReq) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedUserServer) SnsLogin(ctx context.Context, req *AppConfigReq) (*AppUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnsLogin not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserInfo(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SnsLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SnsLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/SnsLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SnsLogin(ctx, req.(*AppConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _User_Ping_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _User_UserInfo_Handler,
		},
		{
			MethodName: "SnsLogin",
			Handler:    _User_SnsLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
